export const FLOTORY_APP_NAME = 'Flotory'

/** Bump when regenerating icons (`npm run icons:generate`) to bust browser + SW cache */
export const FLOTORY_ICON_VERSION = 'gold-cream-f-20260605-webpad'

/** Official logo mark — exports generated by `scripts/generate-brand-icons.py` */
export const FLOTORY_ICON_192 = `/icons/icon-192.png?v=${FLOTORY_ICON_VERSION}`
export const FLOTORY_ICON_512 = `/icons/icon-512.png?v=${FLOTORY_ICON_VERSION}`
